apiVersion: v2
name: uptime-kuma
description: A Helm chart for Uptime Kuma - A self-hosted monitoring tool

# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.23.16"

# Additional metadata
keywords:
  - monitoring
  - uptime
  - status-page
  - self-hosted
home: https://github.com/louislam/uptime-kuma
sources:
  - https://github.com/louislam/uptime-kuma
  - https://github.com/SKILLAB-DevOps/helm-uptime-kuma
maintainers:
  - name: SKILLAB-DevOps
    url: https://github.com/SKILLAB-DevOps
icon: https://raw.githubusercontent.com/louislam/uptime-kuma/master/public/icon.png
annotations:
  category: Monitoring
